### ISSUE TITLE
question more than an issue

### ISSUE THREAD

**Issue by edwardsmarkf** [ImageMagick/MagickWandForPHP#2]
hello - i used to follow the following script to install MagicWandForPHP:

```
curl  http://www.magickwand.org/download/php/MagickWandForPHP-1.0.9-2.tar.gz | tar -xzf  - ;
cd ./MagickWandForPHP* ;
phpize ;
./configure --with-magickwand=/opt/imagemagick/ ;
make && make test && make install ;
```
dumb question, but is this maintained anymore?  i see the domain name has gone away.

i take it i need to seriously update my instructions?

**Comment by urban-warrior** [comment]
MagickWandForPHP has essentially been replaced by IMagick.  MagickWandForPHP has been orphaned.  We keep it in case an ImageMagick user wants to volunteer to maintain/enhance the project.

**Comment by edwardsmarkf** [comment]
wow, and i did not even get an opportunity to say goodbye.   kinda sad...  😥

oh well, now onto more current issues:

https://github.com/ImageMagick/ImageMagick/discussions/2521
